Martography/Areas/Administration/Controllers/ProjectController.cs
using ViewModels.Images;
using ViewModels.ProjectModels;
using Services.Data.Interfaces;

using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using ViewModels.GalleryModels;

namespace Martography.Areas.Administration.Controllers
{
    public class ProjectController : AdministrationController
    {
        private readonly IProjectsService projectsService;
        private readonly IImageService imageService;
        private readonly IGalleryService galleryService;

        public ProjectController(IProjectsService projectsService, IImageService imageService, IGalleryService galleryService)
        {
            this.projectsService = projectsService;
            this.imageService = imageService;
            this.galleryService = galleryService;
        }

        public async Task<IActionResult> Index(string id)
        {
            var singleProject = await projectsService.GetProjectByIdForAdmin<AdminProjectViewModel>(id);
            singleProject.AllGalleries = await galleryService.GetAllGalleriesForAdmin<GalleryDropDownViewModel>();

            return View(singleProject);
        }

        [HttpPost]
        public async Task<IActionResult> Upload(ImagesUploadViewModel model)
        {
            var imagesList = new List<ImageUploadViewModel>();

            foreach (var i in model.Images)
            {
                imagesList.Add(new ImageUploadViewModel()
                {
                    Name = i.FileName,
                    GalleryName = model.galleryName,
                    ProjectName = model.projectName,
                    Type = i.ContentType,
                    Content = i.OpenReadStream()
                });
            }
            //Upload to the File System
            await imageService.SaveImages(imagesList, model.projectId);

            //foreach (var image in model.Images)
            //{
            //    //Upload to the databse
            //    await imageService.InsertImage(image.FileName, model.projectId);
            //}

            return RedirectToAction(nameof(this.Index), new { id = model.projectId });
        }

        public async Task<IActionResult> Edit(string projectId)
        {
            var singleProject = await projectsService.GetProjectByIdForAdmin<AdminProjectViewModel>(projectId);

            return View(singleProject);
        }

        [HttpPost]
        public async Task<IActionResult> ChangeToGallery(string galleryId, string projectId, bool setDeleted)
        {
            if (setDeleted == false)
            {
                await projectsService.UnDeleteProject(projectId);
                await projectsService.MoveProjectToGalleryForAdmin(galleryId, projectId);
            }
            else
            {
                await projectsService.DeleteProject(projectId);
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> CreateProject(string name, string galleryId, string description)
        {
            await projectsService.CreateProject(name, description, galleryId);
            return RedirectToAction("Index", "Home");

        }

        [HttpPost]
        public async Task<IActionResult> CreateGallery(string name, string description, bool isPrivate)
        {
            await galleryService.CreateGallery(name, description, isPrivate);
            return RedirectToAction("Index","Home");
        }
    }
}

Martography/Areas/Administration/Views/Project/Edit.cshtml
@{
    @using System.Linq;
    @using ViewModels.ProjectModels;
    @model AdminProjectViewModel
}

<div class="wrapper light-wrapper">
    <div class="container inner pt-70 text-center">
        <h1 class="post-title">@Model.Name<span class="small"><i> in @Model.GalleryName</i></span></h1>

        @* Make each row form and submit all or use ajax or FIND another solution *@
        <form id="editForm" method="post">
            <input type="hidden" />
            <div class="row">
                @{ var style = "border-style: solid; border-width: thin;"; }
                @foreach (var image in Model.Images.OrderByDescending(i => i.Position.HasValue).ThenBy(i => i.Position))
                {
                    <div class="col-md-3" style="@(Model.Images.ToList().FindIndex(x=>x == image) % 2 == 0 ? style : "")">
                        <div class="row">
                            <div class="col">
                                <img src="~/@image.ThumbnailImageUrl" width="115" />
                                <input type="hidden" value="@image.Id" />
                            </div>
                        </div>
                        <div class="row justify-content-center">
                            <label>@image.Name</label>
                        </div>
                        <div class="row justify-content-center">
                            <textarea style="height: 5rem; width:auto;" id="@(image.Id + "description")" placeholder="Description">@image.Description</textarea>
                        </div>

                        <div class="row justify-content-center">
                            <div class="col-6">
                                <label class="float-right" for="@(image.Id + "position")">Position</label>
                            </div>
                            <div class="col-6">
                                <input type="number" id="@(image.Id + "position")" value="@image.Position" style="width: 6rem; float: left;" />
                            </div>
                        </div>

                        <div class="row">
                            <div class="col">
                                <label for="@(image.Id + "projThumbnail")">Project thumbnail</label>
                                <input type="checkbox" class="thumbnailCheckbox" id="@(image.Id + "projThumbnail")" checked="@image.IsProjectThumbnail" />
                            </div>
                        </div>

                        <div class="row">
                            <div class="col">
                                <label class="text-success" for="@(image.Id + "home")">Show on home page carousel.</label>
                                <input type="checkbox" id="@(image.Id + "home")" checked="@image.ShowOnHomePageCarousel" />
                            </div>
                        </div>

                        <div class="row">
                            <div class="col">
                                <label class="text-info" for="@(image.Id + "homeGallery")">Show on home page gallery.</label>
                                <input type="checkbox" id="@(image.Id + "homeGallery")" checked="@image.ShowOnHomePageGallery" />
                            </div>
                        </div>

                        <div class="row">
                            <div class="col">
                                <label class="text-danger" for="@(image.Id + "delete")">Set as deleted</label>
                                <input type="checkbox" id="@(image.Id + "delete")" checked="@image.IsDeleted" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </form>
        <div class="text-center"><button class="btn btn-outline-primary" style="background-color: black;" onclick="postToProject()">Save changes</button></div>
    </div>
</div>

@section Scripts{
    <script>

        var checkboxes = $('.thumbnailCheckbox');

        checkboxes.change(function () {
            if ($(checkboxes).is(':checked')) { checkboxes.not(this).prop('checked', false); }
        });

        function postToProject() {
            var colDivs = $('.col-md-3');
            var dataSet = new Array();

            for (col of colDivs) {
                var id = col.children[0].children[0].children[1].value
                var description = $(`#${id}description`).val();
                var position = $(`#${id}position`).val();
                var isThumbnail = $(`#${id}projThumbnail`).is(":checked");
                var isOnHomePageCarousel = $(`#${id}home`).is(":checked");
                var isOnHomePageGallery = $(`#${id}homeGallery`).is(":checked");
                var isDeleted = $(`#${id}delete`).is(":checked");

                if (position === "") { position = null; }

                dataSet.push({
                    id,
                    description,
                    position,
                    isThumbnail,
                    isOnHomePageCarousel,
                    isOnHomePageGallery,
                    isDeleted
                });
            }

            var token = $("#editForm input[name=__RequestVerificationToken]").val();

            $.ajax({
                url: '/api/admin/EditImages',
                type: "POST",
                headers: { 'RequestVerificationToken': token },
                contentType: 'application/json',
                data: JSON.stringify(dataSet),
                success: function (data) {
                    console.log(data)
                    location.reload(true);
                },
                error: function (req, status, error) {
                    console.log(error);
                    console.log(req);
                    console.log(status);
                }
            });
        }
    </script>
}

Martography/Areas/Administration/Views/Project/Index.cshtml
@{
    @using ViewModels.ProjectModels;
    @model AdminProjectViewModel
}

<div class="wrapper light-wrapper">
    <div class="container inner pt-70 text-center">

        <form asp-action="Upload" method="post" enctype="multipart/form-data" class="mb-70">
            <div class="row border border-secondary rounded p-2 align-items-center">
                <div class="col">
                    <label for="formFileMultiple" class="form-label">Choose images to upload in current project:</label>
                </div>
                <div class="col" align="center">
                    <input class="form-control-file" name="Images" type="file" id="formFileMultiple" multiple style="width: auto;">
                    @*<span asp-validation-for="Images"></span>*@
                </div>
                <input type="hidden" value="@Model.Id" name="projectId" />
                <input type="hidden" value="@Model.Name" name="projectName" />
                <input type="hidden" value="@Model.GalleryName" name="galleryName" />
                <div class="col">
                    <button type="submit" style="background-color: black;" class="btn btn-outline-primary float-left mb-0">Upload</button>
                </div>
            </div>
        </form>

        @if (Model.Images.Count() > 0)
        {
            <div><a class="btn" asp-action="Edit" asp-route-projectId="@Model.Id">Edit Images</a></div>
        }
        <div class="row">
            <div class="col">
                <form id="changeGalleryForm" method="post">
                    <input type="hidden" />
                    <input type="hidden" name="projectId" value="@Model.Id" />
                    <label class="custom-control-label" for="galleryId">Change to gallery:</label>
                    <div class="form-group custom-select-wrapper">
                        <select class="custom-select w-25" name="galleryId">
                            @foreach (var gallery in Model.AllGalleries)
                            {
                                if (Model.GalleryId == gallery.Id)
                                {
                                    <option value="@gallery.Id" selected>@gallery.Name</option>
                                }
                                else
                                {
                                    <option value="@gallery.Id">@gallery.Name</option>
                                }
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        @if (Model.IsDeleted)
                        {
                            <label for="setDeletedProj" class="text-success">Undelete project</label>
                        }
                        else
                        {
                            <label for="setDeletedProj" class="text-danger">Set as DELETED</label>
                        }
                        <input id="setDeletedProj" type="checkbox" name="setDeleted" asp-for="@Model.IsDeleted" />
                    </div>
                </form>
            </div>
        </div>
        <div><button form="changeGalleryForm" type="submit" class="btn" style="background-color: black;" asp-controller="Project" asp-action="ChangeToGallery">Submit changes</button></div>

        <h1 class="post-title">@Model.Name<span class="small"><i> in @Model.GalleryName</i></span></h1>
        <p>
            Nullam id dolor id nibh ultricies vehicula ut id elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Lorem ipsum dolor sit amet, consectetur
            adipiscing elit. Maecenas sed diam eget risus varius blandit sit amet non magna.
        </p>
        <div class="space30"></div>
        <div id="cube-grid" class="cbp light-gallery">
            <!--<div class="cbp-item">
                <figure class="overlay overlay3 rounded">
                    <a href="~/style/images/art/jp1-full.jpg" data-sub-html="#caption1">
                        <img src="~/style/images/art/jp1.jpg" alt="" />
                        <div id="caption1" class="d-none">
                            <p>Cras mattis consectetur purus sit amet fermentum.</p>
                        </div>
                    </a>
                </figure>
            </div>-->
            <!--/.cbp-item -->
            <!--<div class="cbp-item">
                <figure class="overlay overlay3 rounded"><a href="~/style/images/art/jp2-full.jpg"><img src="~/style/images/art/jp2.jpg" alt="" /></a></figure>
            </div>-->
            <!--/.cbp-item -->
            <!--<div class="cbp-item">
                <figure class="overlay overlay3 rounded">
                    <a href="~/style/images/art/jp3-full.jpg" data-sub-html="#caption2">
                        <img src="~/style/images/art/jp3.jpg" alt="" />
                        <div id="caption2" class="d-none">
                            <p>Nulla vitae elit libero, a pharetra augue.</p>
                        </div>
                    </a>
                </figure>
            </div>-->
            <!--/.cbp-item -->
            <!--<div class="cbp-item">
                <figure class="overlay overlay3 rounded"><a href="~/style/images/art/jp4-full.jpg"><img src="~/style/images/art/jp4.jpg" alt="" /></a></figure>
            </div>-->
            @foreach (var image in Model.Images)
            {
                <div class="cbp-item">
                    <figure class="overlay overlay3 rounded"><a href="~/@(image.FullSizeImageUrl)"><img src="~/@(image.ThumbnailImageUrl)" alt="" /></a></figure>
                </div>
            }
        </div>

        @if (Model.Images.Count() <= 0)
        {
            <div class="text-center"><span class="text-danger font-italic">No images found in the current project</span></div>
        }
    </div>
</div>