Martography/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using Services.Data.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ViewModels.About;
using ViewModels.Testimonials;

namespace Martography.Controllers
{
    public class AboutController : Controller
    {
        private readonly ITestimonialService service;

        public AboutController(ITestimonialService service)
        {
            this.service = service;
        }
        public async Task<IActionResult> Index()
        {
            var model = new AboutPageViewModel()
            {
                AllTestimonials = await service.GetAllApproved<TestimonialViewModel>()
            };
            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Index(AboutPageViewModel aboutPageModel)
        {
            if (!ModelState.IsValid)
                return View();

            await service.Create(aboutPageModel.TestimonialFormModel.PersonName, 
                aboutPageModel.TestimonialFormModel.Company, aboutPageModel.TestimonialFormModel.Position, 
                aboutPageModel.TestimonialFormModel.EmailAddress, aboutPageModel.TestimonialFormModel.Content);

            return RedirectToAction(nameof(this.Index));
        }
    }
}

Martography/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;
using Services.Data.Interfaces;
using System.Threading.Tasks;
using ViewModels.Blog;

namespace Martography.Controllers
{
    public class BlogController : Controller
    {
        private readonly IBlogService blogService;

        public BlogController(IBlogService blogService)
        {
            this.blogService = blogService;
        }

        public async Task<IActionResult> Index()
        {
            var allposts = await blogService.GetAll<BlogPostViewModel>();
            return View(allposts);
        }

        public async Task<IActionResult> ById(string Id)
        {
            var post = await blogService.GetPostById<BlogPostViewModel>(Id);
            return View(post);
        }
    }
}

Martography/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using Services.Data.Interfaces;
using System.Threading.Tasks;
using ViewModels.Contact;

namespace Martography.Controllers
{
    public class ContactController : Controller
    {
        private readonly IEmailService emailService;

        public ContactController(IEmailService emailService)
        {
            this.emailService = emailService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(ContactFormViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var isSuccessfull = await emailService.Send(model.Email, model.Subject, model.Message, model.Name);

            return View("ContactFormSubmissionConfirmation", isSuccessfull);
        }
    }
}

Martography/Controllers/GalleryController.cs
using Microsoft.AspNetCore.Mvc;
using Services.Data.Interfaces;
using System.Linq;
using System.Threading.Tasks;
using ViewModels.GalleryModels;

namespace Martography.Controllers
{
    public class GalleryController : Controller
    {
        private readonly IGalleryService galleryService;

        public GalleryController(IGalleryService galleryService)
        {
            this.galleryService = galleryService;
        }

#nullable enable
        //[HttpGet("/{id}/{slug?}")]
        public async Task<IActionResult> Index(string id, string? slug)
        {
            var gallery = await galleryService.GetGallery<SingleGalleryViewModel>(id);
            gallery.GalleryDropDowns = galleryService.GetAllGalleriesCached<GalleryDropDownViewModel>();
            gallery.Slug = slug;

            TempData["PreviousGalleryId"] = Request.Headers["Referer"].ToString().Split("/").Last();

            return View(gallery);
        }
    }
}

Martography/Views/Shared/Components/Gallery/GalleryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using ViewModels.ProjectModels;

namespace Martography.Views.Shared.Components.Gallery
{
    public class GalleryViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(string galleryId)
        {
            return View();
        }
    }
}

Martography/Views/Shared/_Footer.cshtml
@{ }
<footer class="wrapper white-wrapper">
    <div class="container inner pt-60 pb-30 text-center">
        <div class="row">
            <div class="col-md-10 offset-md-1">
                <div class="row">
                    <div class="col-sm-4 order-sm-12">
                        <div class="widget">
                            <h3 class="widget-title">Follow</h3>
                            <ul class="social social-mute social-s">
                                <li><a href="https://www.instagram.com/martographyph/" target="_blank" class="magic-hover magic-hover__square"><i class="fa fa-instagram fa-2x"></i></a></li>
                                <li><a href="https://www.facebook.com/martographyy" target="_blank" class="magic-hover magic-hover__square"><i class="fa fa-facebook-f fa-2x"></i></a></li>
                                <li><a href="https://500px.com/p/haloho?view=photos" target="_blank" class="magic-hover magic-hover__square"><i class="fa fa-500px fa-2x"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-4 order-sm-1">
                        <div class="widget">
                            <h3 class="widget-title">Location</h3>
                            <address class="mb-0"><a class="black magic-hover magic-hover__square" target="_blank" href="https://www.google.com/maps/@@42.6831905,23.377003,20.28z"> Sofia <br> Bulgaria </a></address>
                        </div>
                    </div>
                    <div class="col-sm-4 order-sm-12">
                        <div class="widget">
                            <a asp-controller="Contact" class="nocolor magic-hover magic-hover__square"><h3 class="widget-title">Contact</h3></a>
                            <a href="mailto:contact@martographyph.com" class="nocolor magic-hover magic-hover__square">contact@martographyph.com</a> <br /> <a class="nocolor" href="tel:+359882721995">+359 88 272 1995</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="space30"></div>
        <p class="text-center">Copyright &copy; @DateTime.Now.Year Martography. All Rights Reserved.</p>
    </div>
</footer>

Martography/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-W2HK6QK5XX"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'G-W2HK6QK5XX');
    </script>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Martography</title>

    @*<link rel="stylesheet" href="~/css/magic-mouse.css" />*@
@*<environment include="Development">*@
    <link rel="shortcut icon" href="~/style/images/favicon.png">
    <link rel="stylesheet" type="text/css" href="~/style/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="~/style/css/plugins.css">
    <link rel="stylesheet" type="text/css" href="~/style/type/icons.css">
    <link rel="stylesheet" type="text/css" href="~/style/css/style.css">
    <link rel="stylesheet" type="text/css" href="~/style/revolution/css/settings.css">
    <link rel="stylesheet" type="text/css" href="~/style/revolution/css/layers.css">
    <link rel="stylesheet" type="text/css" href="~/style/revolution/css/navigation.css">
    <link rel="stylesheet" type="text/css" href="~/style/css/color/lavender.css">
    @*<link href="https://fonts.googleapis.com/css?family=Poppins:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">*@
    <link rel="stylesheet" type="text/css" href="~/style/css/font/font2.css">
@*</environment>*@
    @*<environment exclude="Development">
        <link rel="stylesheet" type="text/css" href="~/css/site.min.css">
    </environment>*@
</head>
<body>
    <div class="content-wrapper">
        <header>
            <vc:navigation-partial></vc:navigation-partial>
        </header>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        <partial name="_Footer" />
    </div>

    @*<script type="text/javascript" src="~/js/magic_mouse.js"></script>*@

    <script src="~/style/js/jquery.min.js"></script>
    <script src="~/style/js/popper.min.js"></script>
    <script src="~/style/js/bootstrap.min.js"></script>
    <script src="~/style/js/plugins.js"></script>
    <script src="~/style/js/scripts.js"></script>
    <script src="~/style/revolution/js/jquery.themepunch.tools.min.js"></script>
    <script src="~/style/revolution/js/jquery.themepunch.revolution.min.js"></script>


    @*<script type="text/javascript">
            options = {
                "cursorOuter": "circle-basic",
                "hoverEffect": "pointer-blur",
                "hoverItemMove": false,
                "defaultCursor": false,
                "outerWidth": 40,
                "outerHeight": 40
            };
            magicMouse(options);
        </script>*@


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Martography/Views/Shared/_NavigationPartial.cshtml
@{ 
    var urlPath = Context.Request.Path;
    string classContent = urlPath == "/" ? "navbar wide transparent absolute inverse-text navbar-expand-lg" : "navbar wide transparent absolute text navbar-expand-lg";
}

<nav class="navbar wide bg-light navbar-expand-lg">
    <div class="container-fluid flex-row justify-content-center">
        <div class="navbar-header">
            <div class="navbar-brand"><a href="/"><img src="#" srcset="~/style/images/logo2.png 1x, style/images/logo2@2x.png 2x" alt="" /></a></div>
            <div class="navbar-hamburger ml-auto d-lg-none d-xl-none"><button class="hamburger animate" data-toggle="collapse" data-target=".navbar-collapse"><span></span></button></div>
        </div>
        <!-- /.navbar-header -->
        <div class="navbar-collapse collapse justify-content-between align-items-center">
            <ul class="navbar-nav plain mx-auto text-center">
                <li class="nav-item">
                    <a class="nav-link magic-hover magic-hover__square" href="/">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle magic-hover magic-hover__square" asp-controller="Portfolio" asp-action="Index">Portfolio</a>
                    <ul class="dropdown-menu">
                        <li class="nav-item"><a asp-controller="Gallery" asp-action="Index" class="dropdown-item magic-hover magic-hover__square" >Portraits</a></li>
                        <li class="nav-item"><a asp-controller="Gallery" asp-action="Index" class="dropdown-item magic-hover magic-hover__square" >Landscapes</a></li>
                        <li class="nav-item"><a asp-controller="Gallery" asp-action="Index" class="dropdown-item magic-hover magic-hover__square" >Cars</a></li>
                        <li class="nav-item"><a asp-controller="Gallery" asp-action="Index" class="dropdown-item magic-hover magic-hover__square" >Nature</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown magic-hover magic-hover__square">
                    <a class="nav-link dropdown-toggle" asp-controller="Blog" asp-action="Index">Blog</a>
                    <ul class="dropdown-menu">
                        <li class="nav-item"><a class="dropdown-item" href="blog.html">Classic View No Sidebar</a></li>
                        <li class="nav-item"><a class="dropdown-item" href="blog2.html">Classic View with Sidebar</a></li>
                        <li class="nav-item"><a class="dropdown-item" href="blog3.html">Grid View I</a></li>
                        <li class="nav-item"><a class="dropdown-item" href="blog4.html">Grid View II</a></li>
                        <li class="nav-item"><a class="dropdown-item" href="blog5.html">Box Style with Sidebar</a></li>
                        <li class="nav-item dropdown">
                            <a class="dropdown-item dropdown-toggle" href="#">Blog Posts</a>
                            <ul class="dropdown-menu">
                                <li class="nav-item"><a class="dropdown-item" href="blog-post.html">Post No Sidebar</a></li>
                                <li class="nav-item"><a class="dropdown-item" href="blog-post2.html">Post with Sidebar</a></li>
                                <li class="nav-item"><a class="dropdown-item" href="blog-post3.html">Post with Box Style</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="About">About me</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link dropdown-toggle" asp-controller="Contact" asp-action="Index">Contact</a>
                </li>
            </ul>
        </div>
        <div class="social-wrapper text-right">
            <ul class="social social-mute social-s mb-0">
                <li><a href="#" class="magic-hover magic-hover__square"><i class="fa fa-instagram"></i></a></li>
                <li><a href="#" class="magic-hover magic-hover__square"><i class="fa fa-facebook-f"></i></a></li>
                <li><a href="#" class="magic-hover magic-hover__square"><i class="fa fa-pinterest"></i></a></li>
                <li><a href="#" class="magic-hover magic-hover__square"><i class="fa fa-500px"></i></a></li>
            </ul>
        </div>
        <!--/.social-wrapper -->
    </div>
</nav>